env:
  browser: true
  es6: true
  jest: true
  cypress/globals: true
extends:
  - "plugin:cypress/recommended"
#   - "plugin:react/recommended"
#   - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
rules:
  "max-len": ["error", { "code": 120 }]
  "no-extra-boolean-cast": 0
  react/jsx-filename-extension:
    - 1
    - extensions: [".js", ".jsx"]
  "object-curly-newline": ["error", {
    "ObjectExpression": { "multiline": true, "consistent": true, "minProperties": 6 },
    "ObjectPattern": { "multiline": true, "consistent": true, "minProperties": 6 },
    "ImportDeclaration": { "multiline": true, "consistent": true, "minProperties": 6 },
    "ExportDeclaration": { "multiline": true, "consistent": true, "minProperties": 6 }
  }]
